### ISSUE TITLE
Build fails on: Stanbol Transformation Connector

### ISSUE THREAD

**Issue by afduarte** [zaizi/sensefy-connectors#1]
Throws error:
`[ERROR] Failed to execute goal on project mcf-stanbol-connector: Could not resolve dependencies for project org.apache.manifoldcf:mcf-stanbol-connector:jar:2.2: Could not find artifact org.apache.stanbol:client:jar:1.1-jaxrs-1.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]`

when running with: `mvn clean install -DskipTests=true`

**Comment by dileepajayakody** [comment]
Hi,
This is because the stanbol.client artifact is not there in maven central.

Please checkout and build the latest stanbol client: 1.3-jaxrs-1.1 version from here : 
https://github.com/zaizi/apache-stanbol-client/tree/jaxrs-1.0

Also please update the version of org.apache.stanbol.client maven dependency in the mcf-stanbol-connector project to 1.3-jaxrs-1.1.

Please let us know if you need further assistance.

**Comment by afduarte** [comment]
Thanks, I was able to build with that. The problem was indeed the version of org.apache.stanbol.client maven dependency in the mcf-stanbol-connector project.
